apiVersion: krm.kcl.dev/v1alpha1
kind: KCLRun
metadata:
  name: validate-container-requests
  annotations: 
    krm.kcl.dev/version: 0.0.1
    krm.kcl.dev/type: validation
    documentation: >-
      Requires containers to have memory and CPU requests set and constrains
      requests to be within the specified maximum values.

      https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
spec:
  params:
    cpu: "200m"
    memory: "1Gi"
  source: ./examples/validation/validate-container-requests/main.k
---
apiVersion: v1
kind: Pod
metadata:
  name: allowed
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          cpu: "100m"
          memory: "1Gi"
