apiVersion: krm.kcl.dev/v1alpha1
kind: KCLRun
metadata:
  name: add-psa-labels
  annotations: 
    krm.kcl.dev/version: 0.0.1
    krm.kcl.dev/type: mutation
    documentation: >-
      Pod Security Admission (PSA) can be controlled via the assignment of labels
      at the Namespace level which define the Pod Security Standard (PSS) profile
      in use and the action to take. If not using a cluster-wide configuration
      via an AdmissionConfiguration file, Namespaces must be explicitly labeled.
      This policy assigns the labels `pod-security.kubernetes.io/enforce=baseline`
      and `pod-security.kubernetes.io/warn=restricted` to all new Namespaces if
      those labels are not included.
spec:
  source: ./examples/mutation/add-psa-labels/main.k
---
apiVersion: v1
kind: Namespace
metadata:
  name: sampleapp
