apiVersion: krm.kcl.dev/v1alpha1
kind: KCLRun
metadata:
  name: add-capabilities
  annotations: 
    krm.kcl.dev/version: 0.0.1
    krm.kcl.dev/type: mutation
    documentation: >-
      In the earlier Pod Security Policy controller, it was possible to configure a policy
      to add capabilities to containers within a Pod. This made it easier to assign some basic defaults
      rather than blocking Pods or to simply provide capabilities for certain workloads if not specified.
      This policy mutates Pods to add the capabilities SETFCAP and SETUID so long as they are not listed
      as dropped capabilities first.
spec:
  source: ./examples/mutation/add-capabilities/main.k
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
