apiVersion: krm.kcl.dev/v1alpha1
kind: KCLRun
metadata:
  name: disallow-ingress-wildcard
  annotations: 
    krm.kcl.dev/version: 0.0.1
    krm.kcl.dev/type: validation
    documentation: >-
      A validation that prevents the creation of Ingress resources with a blank or wildcard (*) hostname since
      that would enable them to intercept traffic for other services in the cluster, even if they don't have
      access to those services.
spec:
  source: ./examples/validation/disallow-ingress-wildcard/main.k
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: non-wildcard-ingress
spec:
  rules:
  - host: 'myservice.example.com'
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: example
            port:
              number: 80
