apiVersion: krm.kcl.dev/v1alpha1
kind: KCLRun
metadata:
  name: psp-capabilities
  annotations: 
    krm.kcl.dev/version: 0.0.1
    krm.kcl.dev/type: validation
    documentation: >-
      Controls Linux capabilities on containers. Corresponds to the
      `allowedCapabilities` and `requiredDropCapabilities` fields in a
      PodSecurityPolicy. For more information, see
      https://kubernetes.io/docs/concepts/policy/pod-security-policy/#capabilities
spec:
  params:
    allowedCapabilities: ["something"]
    requiredDropCapabilities: ["must_drop"]
  source: ./examples/validation/psp-capabilities/main.k
---
apiVersion: v1
kind: Pod
metadata:
  name: disallowed
  labels:
    owner: me.agilebank.demo
spec:
  containers:
    - name: kcl
      image: kcllang/kcl
      securityContext:
        capabilities:
          add: ["disallowedcapability"]
      resources:
        limits:
          cpu: "100m"
          memory: "30Mi"
