apiVersion: krm.kcl.dev/v1alpha1
kind: KCLRun
metadata:
  name: readonly-root-fs
  annotations: 
    krm.kcl.dev/version: 0.0.1
    krm.kcl.dev/type: mutation
    documentation: >-
      Set read only root file system for containers
spec:
  source: ./examples/mutation/readonly-root-fs/main.k
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
