apiVersion: krm.kcl.dev/v1alpha1
kind: KCLRun
metadata:
  name: required-labels
  annotations: 
    krm.kcl.dev/version: 0.0.1
    krm.kcl.dev/type: validation
    documentation: >-
      Requires resources to contain specified labels, with values matching provided regular expressions.
spec:
  params:
    requires:
      - key: config.kubernetes.io/local-config
        # Optional: If specified, a regular expression the annotation's value must match.
        allowedRegex: "true"
  source: ./examples/validation/required-labels/main.k
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bad-required-labels
  labels:
    config.kubernetes.io/local-config: "false"
spec:
  rules:
  - host: cafe.example.com
    http:
      paths:
      - path: /root
        pathType: Prefix
        backend:
          service:
            name: tea-svc
            port:
              number: 80
