apiVersion: krm.kcl.dev/v1alpha1
kind: KCLRun
metadata:
  name: whoami-yaml
  annotations: 
    krm.kcl.dev/version: 0.0.1
    krm.kcl.dev/type: abstraction
    documentation: >-
      whoami application abstraction written by YAML
spec:
  source: ./examples/abstraction/whoami-yaml/main.k
