apiVersion: krm.kcl.dev/v1alpha1
kind: KCLRun
metadata:
  name: add-linkerd-policy-annotation
  annotations: 
    krm.kcl.dev/version: 0.0.1
    krm.kcl.dev/type: mutation
    documentation: >-
      Add Linkerd Policy Annotation
spec:
  source: ./examples/mutation/add-linkerd-policy-annotation/main.k
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
