apiVersion: krm.kcl.dev/v1alpha1
kind: KCLRun
metadata:
  name: set-labels
  annotations: 
    krm.kcl.dev/version: 0.0.1
    krm.kcl.dev/type: mutation
    documentation: >-
      Set labels
spec:
  params:
    labels:
      config.kubernetes.io/local-config: "true"
  source: ./examples/mutation/set-labels/main.k
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
