apiVersion: krm.kcl.dev/v1alpha1
kind: KCLRun
metadata:
  name: add-nodeselector
  annotations: 
    krm.kcl.dev/version: 0.0.1
    krm.kcl.dev/type: mutation
    documentation: >-
      Add nodeselector
spec:
  params:
    selector:
      foo: bar
  source: ./examples/mutation/add-nodeselector/main.k
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
