apiVersion: krm.kcl.dev/v1alpha1
kind: KCLRun
metadata:
  name: disallow-anonymous
  annotations: 
    krm.kcl.dev/version: 0.0.1
    krm.kcl.dev/type: validation
    documentation: >-
      Disallows associating ClusterRole and Role resources 
      to the system:anonymous user and system:unauthenticated group.
spec:
  params:
    allowedRoles: 
      - cluster-role-1
  source: ./examples/validation/disallow-anonymous/main.k
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-role-binding-2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-role-2
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:unauthenticated
