apiVersion: krm.kcl.dev/v1alpha1
kind: KCLRun
metadata:
  name: restrict-ingress-paths
  annotations: 
    krm.kcl.dev/version: 0.0.1
    krm.kcl.dev/type: validation
    documentation: >-
      This policy mitigates CVE-2021-25745 by restricting `spec.rules[].http.paths[].path` to safe values.
      Additional paths can be added as required. This issue has been fixed in NGINX Ingress v1.2.0. 
      Please refer to the CVE for details.
spec:
  source: ./examples/validation/nginx-ingress/restrict-ingress-paths/main.k
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: good-paths
spec:
  rules:
  - host: cafe.example.com
    http:
      paths:
      - path: /tea
        pathType: Prefix
        backend:
          service:
            name: tea-svc
            port:
              number: 80
      - path: /coffee
        pathType: Prefix
        backend:
          service:
            name: coffee-svc
            port:
              number: 80
