apiVersion: krm.kcl.dev/v1alpha1
kind: KCLRun
metadata:
  name: add-istio-sidecar-injection
  annotations: 
    krm.kcl.dev/version: 0.0.1
    krm.kcl.dev/type: mutation
    documentation: >-
      In order for Istio to inject sidecars to workloads deployed into Namespaces,
      the label `istio-injection` must be set to `enabled`. As an alternative to
      rejecting Namespace definitions which don't already contain this label,
      it can be added automatically. This policy adds the label `istio-inject`
      set to `enabled` for all new Namespaces.
spec:
  source: ./examples/mutation/add-istio-sidecar-injection/main.k
---
apiVersion: v1
kind: Namespace
metadata:
  name: sampleapp
